/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lti.itops.ipac.custcatmgmt.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the TTDPSPCustDecisionTaskTable service. Represents a row in the &quot;IPAC_CUST_CAT_MGMT_TTDPSPCustDecisionTaskTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lti.itops.ipac.custcatmgmt.model.impl.TTDPSPCustDecisionTaskTableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lti.itops.ipac.custcatmgmt.model.impl.TTDPSPCustDecisionTaskTableImpl}.
 * </p>
 *
 * @author sunprabh
 * @see TTDPSPCustDecisionTaskTable
 * @see com.lti.itops.ipac.custcatmgmt.model.impl.TTDPSPCustDecisionTaskTableImpl
 * @see com.lti.itops.ipac.custcatmgmt.model.impl.TTDPSPCustDecisionTaskTableModelImpl
 * @generated
 */
@ProviderType
public interface TTDPSPCustDecisionTaskTableModel extends BaseModel<TTDPSPCustDecisionTaskTable> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ttdpsp cust decision task table model instance should use the {@link TTDPSPCustDecisionTaskTable} interface instead.
	 */

	/**
	 * Returns the primary key of this ttdpsp cust decision task table.
	 *
	 * @return the primary key of this ttdpsp cust decision task table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ttdpsp cust decision task table.
	 *
	 * @param primaryKey the primary key of this ttdpsp cust decision task table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ttdpsp cust decision task table ID of this ttdpsp cust decision task table.
	 *
	 * @return the ttdpsp cust decision task table ID of this ttdpsp cust decision task table
	 */
	public long getTTDPSPCustDecisionTaskTableId();

	/**
	 * Sets the ttdpsp cust decision task table ID of this ttdpsp cust decision task table.
	 *
	 * @param TTDPSPCustDecisionTaskTableId the ttdpsp cust decision task table ID of this ttdpsp cust decision task table
	 */
	public void setTTDPSPCustDecisionTaskTableId(
		long TTDPSPCustDecisionTaskTableId);

	/**
	 * Returns the sub ttdpsp task customer ID of this ttdpsp cust decision task table.
	 *
	 * @return the sub ttdpsp task customer ID of this ttdpsp cust decision task table
	 */
	public long getSubTTDPSPTaskCustomerId();

	/**
	 * Sets the sub ttdpsp task customer ID of this ttdpsp cust decision task table.
	 *
	 * @param subTTDPSPTaskCustomerId the sub ttdpsp task customer ID of this ttdpsp cust decision task table
	 */
	public void setSubTTDPSPTaskCustomerId(long subTTDPSPTaskCustomerId);

	/**
	 * Returns the condition of this ttdpsp cust decision task table.
	 *
	 * @return the condition of this ttdpsp cust decision task table
	 */
	public boolean getCondition();

	/**
	 * Returns <code>true</code> if this ttdpsp cust decision task table is condition.
	 *
	 * @return <code>true</code> if this ttdpsp cust decision task table is condition; <code>false</code> otherwise
	 */
	public boolean isCondition();

	/**
	 * Sets whether this ttdpsp cust decision task table is condition.
	 *
	 * @param condition the condition of this ttdpsp cust decision task table
	 */
	public void setCondition(boolean condition);

	/**
	 * Returns the order of this ttdpsp cust decision task table.
	 *
	 * @return the order of this ttdpsp cust decision task table
	 */
	public int getOrder();

	/**
	 * Sets the order of this ttdpsp cust decision task table.
	 *
	 * @param order the order of this ttdpsp cust decision task table
	 */
	public void setOrder(int order);

	/**
	 * Returns the parent ttdpsp task customer ID of this ttdpsp cust decision task table.
	 *
	 * @return the parent ttdpsp task customer ID of this ttdpsp cust decision task table
	 */
	public long getParentTTDPSPTaskCustomerId();

	/**
	 * Sets the parent ttdpsp task customer ID of this ttdpsp cust decision task table.
	 *
	 * @param parentTTDPSPTaskCustomerId the parent ttdpsp task customer ID of this ttdpsp cust decision task table
	 */
	public void setParentTTDPSPTaskCustomerId(long parentTTDPSPTaskCustomerId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		TTDPSPCustDecisionTaskTable ttdpspCustDecisionTaskTable);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TTDPSPCustDecisionTaskTable> toCacheModel();

	@Override
	public TTDPSPCustDecisionTaskTable toEscapedModel();

	@Override
	public TTDPSPCustDecisionTaskTable toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}