/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lti.itops.ipac.custcatmgmt.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import com.lti.itops.ipac.custcatmgmt.model.TTDPSubProcessCustomerMap;
import com.lti.itops.ipac.custcatmgmt.model.TTDPSubProcessCustomerMapModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the TTDPSubProcessCustomerMap service. Represents a row in the &quot;IPAC_CUST_CAT_MGMT_TTDPSubProcessCustomerMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TTDPSubProcessCustomerMapModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TTDPSubProcessCustomerMapImpl}.
 * </p>
 *
 * @author sunprabh
 * @see TTDPSubProcessCustomerMapImpl
 * @see TTDPSubProcessCustomerMap
 * @see TTDPSubProcessCustomerMapModel
 * @generated
 */
@ProviderType
public class TTDPSubProcessCustomerMapModelImpl extends BaseModelImpl<TTDPSubProcessCustomerMap>
	implements TTDPSubProcessCustomerMapModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ttdp sub process customer map model instance should use the {@link TTDPSubProcessCustomerMap} interface instead.
	 */
	public static final String TABLE_NAME = "IPAC_CUST_CAT_MGMT_TTDPSubProcessCustomerMap";
	public static final Object[][] TABLE_COLUMNS = {
			{ "TTDPSubProcessCustomerId", Types.BIGINT },
			{ "TTDPSubProcessId", Types.BIGINT },
			{ "organizationId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "companyId", Types.BIGINT },
			{ "createdBy", Types.BIGINT },
			{ "createdOn", Types.TIMESTAMP },
			{ "modifiedBy", Types.BIGINT },
			{ "modifiedOn", Types.TIMESTAMP },
			{ "statusId", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("TTDPSubProcessCustomerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("TTDPSubProcessId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdOn", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedOn", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("statusId", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table IPAC_CUST_CAT_MGMT_TTDPSubProcessCustomerMap (TTDPSubProcessCustomerId LONG not null primary key,TTDPSubProcessId LONG,organizationId LONG,name STRING null,companyId LONG,createdBy LONG,createdOn DATE null,modifiedBy LONG,modifiedOn DATE null,statusId INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table IPAC_CUST_CAT_MGMT_TTDPSubProcessCustomerMap";
	public static final String ORDER_BY_JPQL = " ORDER BY ttdpSubProcessCustomerMap.TTDPSubProcessCustomerId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY IPAC_CUST_CAT_MGMT_TTDPSubProcessCustomerMap.TTDPSubProcessCustomerId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.lti.itops.ipac.custcatmgmt.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.lti.itops.ipac.custcatmgmt.model.TTDPSubProcessCustomerMap"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.lti.itops.ipac.custcatmgmt.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.lti.itops.ipac.custcatmgmt.model.TTDPSubProcessCustomerMap"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.lti.itops.ipac.custcatmgmt.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.lti.itops.ipac.custcatmgmt.model.TTDPSubProcessCustomerMap"),
			true);
	public static final long TTDPSUBPROCESSCUSTOMERID_COLUMN_BITMASK = 1L;
	public static final long TTDPSUBPROCESSID_COLUMN_BITMASK = 2L;
	public static final long ORGANIZATIONID_COLUMN_BITMASK = 4L;
	public static final long STATUSID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.lti.itops.ipac.custcatmgmt.service.util.ServiceProps.get(
				"lock.expiration.time.com.lti.itops.ipac.custcatmgmt.model.TTDPSubProcessCustomerMap"));

	public TTDPSubProcessCustomerMapModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _TTDPSubProcessCustomerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTTDPSubProcessCustomerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _TTDPSubProcessCustomerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TTDPSubProcessCustomerMap.class;
	}

	@Override
	public String getModelClassName() {
		return TTDPSubProcessCustomerMap.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("TTDPSubProcessCustomerId", getTTDPSubProcessCustomerId());
		attributes.put("TTDPSubProcessId", getTTDPSubProcessId());
		attributes.put("organizationId", getOrganizationId());
		attributes.put("name", getName());
		attributes.put("companyId", getCompanyId());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("createdOn", getCreatedOn());
		attributes.put("modifiedBy", getModifiedBy());
		attributes.put("modifiedOn", getModifiedOn());
		attributes.put("statusId", getStatusId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long TTDPSubProcessCustomerId = (Long)attributes.get(
				"TTDPSubProcessCustomerId");

		if (TTDPSubProcessCustomerId != null) {
			setTTDPSubProcessCustomerId(TTDPSubProcessCustomerId);
		}

		Long TTDPSubProcessId = (Long)attributes.get("TTDPSubProcessId");

		if (TTDPSubProcessId != null) {
			setTTDPSubProcessId(TTDPSubProcessId);
		}

		Long organizationId = (Long)attributes.get("organizationId");

		if (organizationId != null) {
			setOrganizationId(organizationId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long createdBy = (Long)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date createdOn = (Date)attributes.get("createdOn");

		if (createdOn != null) {
			setCreatedOn(createdOn);
		}

		Long modifiedBy = (Long)attributes.get("modifiedBy");

		if (modifiedBy != null) {
			setModifiedBy(modifiedBy);
		}

		Date modifiedOn = (Date)attributes.get("modifiedOn");

		if (modifiedOn != null) {
			setModifiedOn(modifiedOn);
		}

		Integer statusId = (Integer)attributes.get("statusId");

		if (statusId != null) {
			setStatusId(statusId);
		}
	}

	@Override
	public long getTTDPSubProcessCustomerId() {
		return _TTDPSubProcessCustomerId;
	}

	@Override
	public void setTTDPSubProcessCustomerId(long TTDPSubProcessCustomerId) {
		_columnBitmask |= TTDPSUBPROCESSCUSTOMERID_COLUMN_BITMASK;

		if (!_setOriginalTTDPSubProcessCustomerId) {
			_setOriginalTTDPSubProcessCustomerId = true;

			_originalTTDPSubProcessCustomerId = _TTDPSubProcessCustomerId;
		}

		_TTDPSubProcessCustomerId = TTDPSubProcessCustomerId;
	}

	public long getOriginalTTDPSubProcessCustomerId() {
		return _originalTTDPSubProcessCustomerId;
	}

	@Override
	public long getTTDPSubProcessId() {
		return _TTDPSubProcessId;
	}

	@Override
	public void setTTDPSubProcessId(long TTDPSubProcessId) {
		_columnBitmask |= TTDPSUBPROCESSID_COLUMN_BITMASK;

		if (!_setOriginalTTDPSubProcessId) {
			_setOriginalTTDPSubProcessId = true;

			_originalTTDPSubProcessId = _TTDPSubProcessId;
		}

		_TTDPSubProcessId = TTDPSubProcessId;
	}

	public long getOriginalTTDPSubProcessId() {
		return _originalTTDPSubProcessId;
	}

	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalOrganizationId) {
			_setOriginalOrganizationId = true;

			_originalOrganizationId = _organizationId;
		}

		_organizationId = organizationId;
	}

	public long getOriginalOrganizationId() {
		return _originalOrganizationId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getName(), languageId,
			useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(LocalizationUtil.updateLocalization(getName(), "Name",
					name, languageId, defaultLanguageId));
		}
		else {
			setName(LocalizationUtil.removeLocalization(getName(), "Name",
					languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(LocalizationUtil.updateLocalization(nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public Date getCreatedOn() {
		return _createdOn;
	}

	@Override
	public void setCreatedOn(Date createdOn) {
		_createdOn = createdOn;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getModifiedOn() {
		return _modifiedOn;
	}

	@Override
	public void setModifiedOn(Date modifiedOn) {
		_modifiedOn = modifiedOn;
	}

	@Override
	public int getStatusId() {
		return _statusId;
	}

	@Override
	public void setStatusId(int statusId) {
		_columnBitmask |= STATUSID_COLUMN_BITMASK;

		if (!_setOriginalStatusId) {
			_setOriginalStatusId = true;

			_originalStatusId = _statusId;
		}

		_statusId = statusId;
	}

	public int getOriginalStatusId() {
		return _originalStatusId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TTDPSubProcessCustomerMap.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(TTDPSubProcessCustomerMap.class.getName(),
				getPrimaryKey(), defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public TTDPSubProcessCustomerMap toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TTDPSubProcessCustomerMap)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TTDPSubProcessCustomerMapImpl ttdpSubProcessCustomerMapImpl = new TTDPSubProcessCustomerMapImpl();

		ttdpSubProcessCustomerMapImpl.setTTDPSubProcessCustomerId(getTTDPSubProcessCustomerId());
		ttdpSubProcessCustomerMapImpl.setTTDPSubProcessId(getTTDPSubProcessId());
		ttdpSubProcessCustomerMapImpl.setOrganizationId(getOrganizationId());
		ttdpSubProcessCustomerMapImpl.setName(getName());
		ttdpSubProcessCustomerMapImpl.setCompanyId(getCompanyId());
		ttdpSubProcessCustomerMapImpl.setCreatedBy(getCreatedBy());
		ttdpSubProcessCustomerMapImpl.setCreatedOn(getCreatedOn());
		ttdpSubProcessCustomerMapImpl.setModifiedBy(getModifiedBy());
		ttdpSubProcessCustomerMapImpl.setModifiedOn(getModifiedOn());
		ttdpSubProcessCustomerMapImpl.setStatusId(getStatusId());

		ttdpSubProcessCustomerMapImpl.resetOriginalValues();

		return ttdpSubProcessCustomerMapImpl;
	}

	@Override
	public int compareTo(TTDPSubProcessCustomerMap ttdpSubProcessCustomerMap) {
		long primaryKey = ttdpSubProcessCustomerMap.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TTDPSubProcessCustomerMap)) {
			return false;
		}

		TTDPSubProcessCustomerMap ttdpSubProcessCustomerMap = (TTDPSubProcessCustomerMap)obj;

		long primaryKey = ttdpSubProcessCustomerMap.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TTDPSubProcessCustomerMapModelImpl ttdpSubProcessCustomerMapModelImpl = this;

		ttdpSubProcessCustomerMapModelImpl._originalTTDPSubProcessCustomerId = ttdpSubProcessCustomerMapModelImpl._TTDPSubProcessCustomerId;

		ttdpSubProcessCustomerMapModelImpl._setOriginalTTDPSubProcessCustomerId = false;

		ttdpSubProcessCustomerMapModelImpl._originalTTDPSubProcessId = ttdpSubProcessCustomerMapModelImpl._TTDPSubProcessId;

		ttdpSubProcessCustomerMapModelImpl._setOriginalTTDPSubProcessId = false;

		ttdpSubProcessCustomerMapModelImpl._originalOrganizationId = ttdpSubProcessCustomerMapModelImpl._organizationId;

		ttdpSubProcessCustomerMapModelImpl._setOriginalOrganizationId = false;

		ttdpSubProcessCustomerMapModelImpl._originalStatusId = ttdpSubProcessCustomerMapModelImpl._statusId;

		ttdpSubProcessCustomerMapModelImpl._setOriginalStatusId = false;

		ttdpSubProcessCustomerMapModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TTDPSubProcessCustomerMap> toCacheModel() {
		TTDPSubProcessCustomerMapCacheModel ttdpSubProcessCustomerMapCacheModel = new TTDPSubProcessCustomerMapCacheModel();

		ttdpSubProcessCustomerMapCacheModel.TTDPSubProcessCustomerId = getTTDPSubProcessCustomerId();

		ttdpSubProcessCustomerMapCacheModel.TTDPSubProcessId = getTTDPSubProcessId();

		ttdpSubProcessCustomerMapCacheModel.organizationId = getOrganizationId();

		ttdpSubProcessCustomerMapCacheModel.name = getName();

		String name = ttdpSubProcessCustomerMapCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			ttdpSubProcessCustomerMapCacheModel.name = null;
		}

		ttdpSubProcessCustomerMapCacheModel.companyId = getCompanyId();

		ttdpSubProcessCustomerMapCacheModel.createdBy = getCreatedBy();

		Date createdOn = getCreatedOn();

		if (createdOn != null) {
			ttdpSubProcessCustomerMapCacheModel.createdOn = createdOn.getTime();
		}
		else {
			ttdpSubProcessCustomerMapCacheModel.createdOn = Long.MIN_VALUE;
		}

		ttdpSubProcessCustomerMapCacheModel.modifiedBy = getModifiedBy();

		Date modifiedOn = getModifiedOn();

		if (modifiedOn != null) {
			ttdpSubProcessCustomerMapCacheModel.modifiedOn = modifiedOn.getTime();
		}
		else {
			ttdpSubProcessCustomerMapCacheModel.modifiedOn = Long.MIN_VALUE;
		}

		ttdpSubProcessCustomerMapCacheModel.statusId = getStatusId();

		return ttdpSubProcessCustomerMapCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{TTDPSubProcessCustomerId=");
		sb.append(getTTDPSubProcessCustomerId());
		sb.append(", TTDPSubProcessId=");
		sb.append(getTTDPSubProcessId());
		sb.append(", organizationId=");
		sb.append(getOrganizationId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", createdOn=");
		sb.append(getCreatedOn());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", modifiedOn=");
		sb.append(getModifiedOn());
		sb.append(", statusId=");
		sb.append(getStatusId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append(
			"com.lti.itops.ipac.custcatmgmt.model.TTDPSubProcessCustomerMap");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>TTDPSubProcessCustomerId</column-name><column-value><![CDATA[");
		sb.append(getTTDPSubProcessCustomerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TTDPSubProcessId</column-name><column-value><![CDATA[");
		sb.append(getTTDPSubProcessId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationId</column-name><column-value><![CDATA[");
		sb.append(getOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdOn</column-name><column-value><![CDATA[");
		sb.append(getCreatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedOn</column-name><column-value><![CDATA[");
		sb.append(getModifiedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusId</column-name><column-value><![CDATA[");
		sb.append(getStatusId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TTDPSubProcessCustomerMap.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TTDPSubProcessCustomerMap.class, ModelWrapper.class
		};
	private long _TTDPSubProcessCustomerId;
	private long _originalTTDPSubProcessCustomerId;
	private boolean _setOriginalTTDPSubProcessCustomerId;
	private long _TTDPSubProcessId;
	private long _originalTTDPSubProcessId;
	private boolean _setOriginalTTDPSubProcessId;
	private long _organizationId;
	private long _originalOrganizationId;
	private boolean _setOriginalOrganizationId;
	private String _name;
	private String _nameCurrentLanguageId;
	private long _companyId;
	private long _createdBy;
	private Date _createdOn;
	private long _modifiedBy;
	private Date _modifiedOn;
	private int _statusId;
	private int _originalStatusId;
	private boolean _setOriginalStatusId;
	private long _columnBitmask;
	private TTDPSubProcessCustomerMap _escapedModel;
}