/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lti.itops.ipac.custcatmgmt.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import com.lti.itops.ipac.custcatmgmt.model.TTDProcessCustomerMap;
import com.lti.itops.ipac.custcatmgmt.model.TTDProcessCustomerMapModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the TTDProcessCustomerMap service. Represents a row in the &quot;IPAC_CUST_CAT_MGMT_TTDProcessCustomerMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TTDProcessCustomerMapModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TTDProcessCustomerMapImpl}.
 * </p>
 *
 * @author sunprabh
 * @see TTDProcessCustomerMapImpl
 * @see TTDProcessCustomerMap
 * @see TTDProcessCustomerMapModel
 * @generated
 */
@ProviderType
public class TTDProcessCustomerMapModelImpl extends BaseModelImpl<TTDProcessCustomerMap>
	implements TTDProcessCustomerMapModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ttd process customer map model instance should use the {@link TTDProcessCustomerMap} interface instead.
	 */
	public static final String TABLE_NAME = "IPAC_CUST_CAT_MGMT_TTDProcessCustomerMap";
	public static final Object[][] TABLE_COLUMNS = {
			{ "TTDProcessCustomerId", Types.BIGINT },
			{ "TTDProcessId", Types.BIGINT },
			{ "organizationId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "companyId", Types.BIGINT },
			{ "createdBy", Types.BIGINT },
			{ "createdOn", Types.TIMESTAMP },
			{ "modifiedBy", Types.BIGINT },
			{ "modifiedOn", Types.TIMESTAMP },
			{ "statusId", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("TTDProcessCustomerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("TTDProcessId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdOn", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedOn", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("statusId", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table IPAC_CUST_CAT_MGMT_TTDProcessCustomerMap (TTDProcessCustomerId LONG not null primary key,TTDProcessId LONG,organizationId LONG,name STRING null,companyId LONG,createdBy LONG,createdOn DATE null,modifiedBy LONG,modifiedOn DATE null,statusId INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table IPAC_CUST_CAT_MGMT_TTDProcessCustomerMap";
	public static final String ORDER_BY_JPQL = " ORDER BY ttdProcessCustomerMap.TTDProcessCustomerId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY IPAC_CUST_CAT_MGMT_TTDProcessCustomerMap.TTDProcessCustomerId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.lti.itops.ipac.custcatmgmt.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.lti.itops.ipac.custcatmgmt.model.TTDProcessCustomerMap"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.lti.itops.ipac.custcatmgmt.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.lti.itops.ipac.custcatmgmt.model.TTDProcessCustomerMap"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.lti.itops.ipac.custcatmgmt.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.lti.itops.ipac.custcatmgmt.model.TTDProcessCustomerMap"),
			true);
	public static final long TTDPROCESSCUSTOMERID_COLUMN_BITMASK = 1L;
	public static final long TTDPROCESSID_COLUMN_BITMASK = 2L;
	public static final long ORGANIZATIONID_COLUMN_BITMASK = 4L;
	public static final long STATUSID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.lti.itops.ipac.custcatmgmt.service.util.ServiceProps.get(
				"lock.expiration.time.com.lti.itops.ipac.custcatmgmt.model.TTDProcessCustomerMap"));

	public TTDProcessCustomerMapModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _TTDProcessCustomerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTTDProcessCustomerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _TTDProcessCustomerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TTDProcessCustomerMap.class;
	}

	@Override
	public String getModelClassName() {
		return TTDProcessCustomerMap.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("TTDProcessCustomerId", getTTDProcessCustomerId());
		attributes.put("TTDProcessId", getTTDProcessId());
		attributes.put("organizationId", getOrganizationId());
		attributes.put("name", getName());
		attributes.put("companyId", getCompanyId());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("createdOn", getCreatedOn());
		attributes.put("modifiedBy", getModifiedBy());
		attributes.put("modifiedOn", getModifiedOn());
		attributes.put("statusId", getStatusId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long TTDProcessCustomerId = (Long)attributes.get("TTDProcessCustomerId");

		if (TTDProcessCustomerId != null) {
			setTTDProcessCustomerId(TTDProcessCustomerId);
		}

		Long TTDProcessId = (Long)attributes.get("TTDProcessId");

		if (TTDProcessId != null) {
			setTTDProcessId(TTDProcessId);
		}

		Long organizationId = (Long)attributes.get("organizationId");

		if (organizationId != null) {
			setOrganizationId(organizationId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long createdBy = (Long)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date createdOn = (Date)attributes.get("createdOn");

		if (createdOn != null) {
			setCreatedOn(createdOn);
		}

		Long modifiedBy = (Long)attributes.get("modifiedBy");

		if (modifiedBy != null) {
			setModifiedBy(modifiedBy);
		}

		Date modifiedOn = (Date)attributes.get("modifiedOn");

		if (modifiedOn != null) {
			setModifiedOn(modifiedOn);
		}

		Integer statusId = (Integer)attributes.get("statusId");

		if (statusId != null) {
			setStatusId(statusId);
		}
	}

	@Override
	public long getTTDProcessCustomerId() {
		return _TTDProcessCustomerId;
	}

	@Override
	public void setTTDProcessCustomerId(long TTDProcessCustomerId) {
		_columnBitmask |= TTDPROCESSCUSTOMERID_COLUMN_BITMASK;

		if (!_setOriginalTTDProcessCustomerId) {
			_setOriginalTTDProcessCustomerId = true;

			_originalTTDProcessCustomerId = _TTDProcessCustomerId;
		}

		_TTDProcessCustomerId = TTDProcessCustomerId;
	}

	public long getOriginalTTDProcessCustomerId() {
		return _originalTTDProcessCustomerId;
	}

	@Override
	public long getTTDProcessId() {
		return _TTDProcessId;
	}

	@Override
	public void setTTDProcessId(long TTDProcessId) {
		_columnBitmask |= TTDPROCESSID_COLUMN_BITMASK;

		if (!_setOriginalTTDProcessId) {
			_setOriginalTTDProcessId = true;

			_originalTTDProcessId = _TTDProcessId;
		}

		_TTDProcessId = TTDProcessId;
	}

	public long getOriginalTTDProcessId() {
		return _originalTTDProcessId;
	}

	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalOrganizationId) {
			_setOriginalOrganizationId = true;

			_originalOrganizationId = _organizationId;
		}

		_organizationId = organizationId;
	}

	public long getOriginalOrganizationId() {
		return _originalOrganizationId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getName(), languageId,
			useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(LocalizationUtil.updateLocalization(getName(), "Name",
					name, languageId, defaultLanguageId));
		}
		else {
			setName(LocalizationUtil.removeLocalization(getName(), "Name",
					languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(LocalizationUtil.updateLocalization(nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public Date getCreatedOn() {
		return _createdOn;
	}

	@Override
	public void setCreatedOn(Date createdOn) {
		_createdOn = createdOn;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getModifiedOn() {
		return _modifiedOn;
	}

	@Override
	public void setModifiedOn(Date modifiedOn) {
		_modifiedOn = modifiedOn;
	}

	@Override
	public int getStatusId() {
		return _statusId;
	}

	@Override
	public void setStatusId(int statusId) {
		_columnBitmask |= STATUSID_COLUMN_BITMASK;

		if (!_setOriginalStatusId) {
			_setOriginalStatusId = true;

			_originalStatusId = _statusId;
		}

		_statusId = statusId;
	}

	public int getOriginalStatusId() {
		return _originalStatusId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TTDProcessCustomerMap.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(TTDProcessCustomerMap.class.getName(),
				getPrimaryKey(), defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public TTDProcessCustomerMap toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TTDProcessCustomerMap)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TTDProcessCustomerMapImpl ttdProcessCustomerMapImpl = new TTDProcessCustomerMapImpl();

		ttdProcessCustomerMapImpl.setTTDProcessCustomerId(getTTDProcessCustomerId());
		ttdProcessCustomerMapImpl.setTTDProcessId(getTTDProcessId());
		ttdProcessCustomerMapImpl.setOrganizationId(getOrganizationId());
		ttdProcessCustomerMapImpl.setName(getName());
		ttdProcessCustomerMapImpl.setCompanyId(getCompanyId());
		ttdProcessCustomerMapImpl.setCreatedBy(getCreatedBy());
		ttdProcessCustomerMapImpl.setCreatedOn(getCreatedOn());
		ttdProcessCustomerMapImpl.setModifiedBy(getModifiedBy());
		ttdProcessCustomerMapImpl.setModifiedOn(getModifiedOn());
		ttdProcessCustomerMapImpl.setStatusId(getStatusId());

		ttdProcessCustomerMapImpl.resetOriginalValues();

		return ttdProcessCustomerMapImpl;
	}

	@Override
	public int compareTo(TTDProcessCustomerMap ttdProcessCustomerMap) {
		long primaryKey = ttdProcessCustomerMap.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TTDProcessCustomerMap)) {
			return false;
		}

		TTDProcessCustomerMap ttdProcessCustomerMap = (TTDProcessCustomerMap)obj;

		long primaryKey = ttdProcessCustomerMap.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TTDProcessCustomerMapModelImpl ttdProcessCustomerMapModelImpl = this;

		ttdProcessCustomerMapModelImpl._originalTTDProcessCustomerId = ttdProcessCustomerMapModelImpl._TTDProcessCustomerId;

		ttdProcessCustomerMapModelImpl._setOriginalTTDProcessCustomerId = false;

		ttdProcessCustomerMapModelImpl._originalTTDProcessId = ttdProcessCustomerMapModelImpl._TTDProcessId;

		ttdProcessCustomerMapModelImpl._setOriginalTTDProcessId = false;

		ttdProcessCustomerMapModelImpl._originalOrganizationId = ttdProcessCustomerMapModelImpl._organizationId;

		ttdProcessCustomerMapModelImpl._setOriginalOrganizationId = false;

		ttdProcessCustomerMapModelImpl._originalStatusId = ttdProcessCustomerMapModelImpl._statusId;

		ttdProcessCustomerMapModelImpl._setOriginalStatusId = false;

		ttdProcessCustomerMapModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TTDProcessCustomerMap> toCacheModel() {
		TTDProcessCustomerMapCacheModel ttdProcessCustomerMapCacheModel = new TTDProcessCustomerMapCacheModel();

		ttdProcessCustomerMapCacheModel.TTDProcessCustomerId = getTTDProcessCustomerId();

		ttdProcessCustomerMapCacheModel.TTDProcessId = getTTDProcessId();

		ttdProcessCustomerMapCacheModel.organizationId = getOrganizationId();

		ttdProcessCustomerMapCacheModel.name = getName();

		String name = ttdProcessCustomerMapCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			ttdProcessCustomerMapCacheModel.name = null;
		}

		ttdProcessCustomerMapCacheModel.companyId = getCompanyId();

		ttdProcessCustomerMapCacheModel.createdBy = getCreatedBy();

		Date createdOn = getCreatedOn();

		if (createdOn != null) {
			ttdProcessCustomerMapCacheModel.createdOn = createdOn.getTime();
		}
		else {
			ttdProcessCustomerMapCacheModel.createdOn = Long.MIN_VALUE;
		}

		ttdProcessCustomerMapCacheModel.modifiedBy = getModifiedBy();

		Date modifiedOn = getModifiedOn();

		if (modifiedOn != null) {
			ttdProcessCustomerMapCacheModel.modifiedOn = modifiedOn.getTime();
		}
		else {
			ttdProcessCustomerMapCacheModel.modifiedOn = Long.MIN_VALUE;
		}

		ttdProcessCustomerMapCacheModel.statusId = getStatusId();

		return ttdProcessCustomerMapCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{TTDProcessCustomerId=");
		sb.append(getTTDProcessCustomerId());
		sb.append(", TTDProcessId=");
		sb.append(getTTDProcessId());
		sb.append(", organizationId=");
		sb.append(getOrganizationId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", createdOn=");
		sb.append(getCreatedOn());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", modifiedOn=");
		sb.append(getModifiedOn());
		sb.append(", statusId=");
		sb.append(getStatusId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.lti.itops.ipac.custcatmgmt.model.TTDProcessCustomerMap");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>TTDProcessCustomerId</column-name><column-value><![CDATA[");
		sb.append(getTTDProcessCustomerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TTDProcessId</column-name><column-value><![CDATA[");
		sb.append(getTTDProcessId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationId</column-name><column-value><![CDATA[");
		sb.append(getOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdOn</column-name><column-value><![CDATA[");
		sb.append(getCreatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedOn</column-name><column-value><![CDATA[");
		sb.append(getModifiedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusId</column-name><column-value><![CDATA[");
		sb.append(getStatusId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TTDProcessCustomerMap.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TTDProcessCustomerMap.class, ModelWrapper.class
		};
	private long _TTDProcessCustomerId;
	private long _originalTTDProcessCustomerId;
	private boolean _setOriginalTTDProcessCustomerId;
	private long _TTDProcessId;
	private long _originalTTDProcessId;
	private boolean _setOriginalTTDProcessId;
	private long _organizationId;
	private long _originalOrganizationId;
	private boolean _setOriginalOrganizationId;
	private String _name;
	private String _nameCurrentLanguageId;
	private long _companyId;
	private long _createdBy;
	private Date _createdOn;
	private long _modifiedBy;
	private Date _modifiedOn;
	private int _statusId;
	private int _originalStatusId;
	private boolean _setOriginalStatusId;
	private long _columnBitmask;
	private TTDProcessCustomerMap _escapedModel;
}