/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lti.itops.ipac.custcatmgmt.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.lti.itops.ipac.custcatmgmt.model.TTechnologyCustomerMap;
import com.lti.itops.ipac.custcatmgmt.service.TTechnologyCustomerMapLocalServiceUtil;

/**
 * The extended model base implementation for the TTechnologyCustomerMap service. Represents a row in the &quot;IPAC_CUST_CAT_MGMT_TTechnologyCustomerMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TTechnologyCustomerMapImpl}.
 * </p>
 *
 * @author sunprabh
 * @see TTechnologyCustomerMapImpl
 * @see TTechnologyCustomerMap
 * @generated
 */
@ProviderType
public abstract class TTechnologyCustomerMapBaseImpl
	extends TTechnologyCustomerMapModelImpl implements TTechnologyCustomerMap {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t technology customer map model instance should use the {@link TTechnologyCustomerMap} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TTechnologyCustomerMapLocalServiceUtil.addTTechnologyCustomerMap(this);
		}
		else {
			TTechnologyCustomerMapLocalServiceUtil.updateTTechnologyCustomerMap(this);
		}
	}
}